use crate::lazy_lock;
use std::collections::HashMap;

#[derive(Clone)]
pub struct Icon {
    glyph: &'static str,
    color: (u8, u8, u8),
}

impl Icon {
    const fn new(glyph: &'static str, color: (u8, u8, u8)) -> Self { Icon { glyph, color } }

    pub fn get_glyph(&self) -> &str { self.glyph }

    pub fn get_color(&self) -> String { format!("\x1b[38;2;{};{};{}m", self.color.0, self.color.1, self.color.2) }
}

lazy_lock! {
    pub static ICONS: HashMap<&'static str, Icon> = {
        let mut m = HashMap::new();
        m.insert("html", Icon::new("\u{f13b}", (228, 79, 57)));
        m.insert("markdown", Icon::new("\u{f853}", (66, 165, 245)));
        m.insert("css", Icon::new("\u{f81b}", (66, 165, 245)));
        m.insert("sass", Icon::new("\u{e603}", (237, 80, 122)));
        m.insert("less", Icon::new("\u{e60b}", (2, 119, 189)));
        m.insert("json", Icon::new("\u{e60b}", (251, 193, 60)));
        m.insert("yaml", Icon::new("\u{e60b}", (244, 68, 62)));
        m.insert("xml", Icon::new("\u{f72d}", (64, 153, 69)));
        m.insert("image", Icon::new("\u{f71e}", (48, 166, 154)));
        m.insert("javascript", Icon::new("\u{e74e}", (255, 202, 61)));
        m.insert("react", Icon::new("\u{e7ba}", (35, 188, 212)));
        m.insert("react_ts", Icon::new("\u{e7ba}", (36, 142, 211)));
        m.insert("settings", Icon::new("\u{f013}", (66, 165, 245)));
        m.insert("typescript", Icon::new("\u{e628}", (3, 136, 209)));
        m.insert("pdf", Icon::new("\u{f724}", (244, 68, 62)));
        m.insert("table", Icon::new("\u{f71a}", (139, 195, 74)));
        m.insert("database", Icon::new("\u{e706}", (255, 202, 61)));
        m.insert("mysql", Icon::new("\u{e704}", (1, 94, 134)));
        m.insert("postgresql", Icon::new("\u{e76e}", (49, 99, 140)));
        m.insert("sqlite", Icon::new("\u{e7c4}", (1, 57, 84)));
        m.insert("csharp", Icon::new("\u{f81a}", (2, 119, 189)));
        m.insert("zip", Icon::new("\u{f410}", (175, 180, 43)));
        m.insert("exe", Icon::new("\u{ebc7}", (229, 77, 58)));
        m.insert("java", Icon::new("\u{f675}", (244, 68, 62)));
        m.insert("c", Icon::new("\u{fb70}", (2, 119, 189)));
        m.insert("cpp", Icon::new("\u{fb71}", (2, 119, 189)));
        m.insert("go", Icon::new("\u{fcd1}", (32, 173, 194)));
        m.insert("python", Icon::new("\u{f81f}", (52, 102, 143)));
        m.insert("rust", Icon::new("\u{e7a8}", (250, 111, 66)));
        m.insert("nodejs", Icon::new("\u{f898}", (139, 195, 74)));
        m.insert("docker", Icon::new("\u{f308}", (1, 135, 201)));
        m.insert("git", Icon::new("\u{e702}", (229, 77, 58)));
        m.insert("vim", Icon::new("\u{e62b}", (67, 160, 71)));
        m.insert("dir", Icon::new("\u{f74a}", (224, 177, 77)));
        m.insert("diropen", Icon::new("\u{fc6e}", (224, 177, 77)));
        m.insert("hiddendir", Icon::new("\u{f755}", (224, 177, 77)));
        m.insert("downloads", Icon::new("\u{f74c}", (76, 175, 80)));
        m.insert("pictures", Icon::new("\u{f74e}", (43, 150, 137)));
        m.insert("music", Icon::new("\u{fb75}", (239, 83, 80)));
        m.insert("videos", Icon::new("\u{f72a}", (253, 154, 62)));
        m.insert("config", Icon::new("\u{e5fc}", (32, 173, 194)));
        m.insert("file", Icon::new("\u{f0214}", (65, 129, 190)));
        m.insert("link", Icon::new("\u{f0337}", (255, 179, 222)));
        m.insert("hiddenfile", Icon::new("\u{f0613}", (65, 129, 190)));
        m.insert("binary", Icon::new("\u{ebc7}", (76, 175, 80)));
        m.insert("css-map", Icon::new("\u{e749}", (66, 165, 245)));
        m.insert("javascript-map", Icon::new("\u{e781}", (255, 202, 61)));
        m.insert("test-jsx", Icon::new("\u{f595}", (35, 188, 212)));
        m.insert("test-js", Icon::new("\u{f595}", (255, 202, 61)));
        m.insert("typescript-def", Icon::new("\u{fbe4}", (3, 136, 209)));
        m.insert("test-ts", Icon::new("\u{f595}", (3, 136, 209)));
        m.insert("visualstudio", Icon::new("\u{e70c}", (173, 99, 188)));
        m.insert("go-mod", Icon::new("\u{fcd1}", (237, 80, 122)));
        m.insert("go-test", Icon::new("\u{fcd1}", (255, 213, 79)));
        m.insert("python-misc", Icon::new("\u{f820}", (130, 61, 28)));
        m.insert("url", Icon::new("\u{f836}", (66, 165, 245)));
        m.insert("console", Icon::new("\u{f68c}", (250, 111, 66)));
        m.insert("word", Icon::new("\u{f72b}", (1, 87, 155)));
        m.insert("certificate", Icon::new("\u{f623}", (249, 89, 63)));
        m.insert("key", Icon::new("\u{f805}", (48, 166, 154)));
        m.insert("font", Icon::new("\u{f031}", (244, 68, 62)));
        m.insert("lib", Icon::new("\u{f831}", (139, 195, 74)));
        m.insert("ruby", Icon::new("\u{e739}", (229, 61, 58)));
        m.insert("gemfile", Icon::new("\u{e21e}", (229, 61, 58)));
        m.insert("fsharp", Icon::new("\u{e7a7}", (55, 139, 186)));
        m.insert("swift", Icon::new("\u{fbe3}", (249, 95, 63)));
        m.insert("powerpoint", Icon::new("\u{f726}", (209, 71, 51)));
        m.insert("video", Icon::new("\u{f72a}", (253, 154, 62)));
        m.insert("virtual", Icon::new("\u{f822}", (3, 155, 229)));
        m.insert("email", Icon::new("\u{f6ed}", (66, 165, 245)));
        m.insert("coffee", Icon::new("\u{f675}", (66, 165, 245)));
        m.insert("document", Icon::new("\u{f718}", (66, 165, 245)));
        m.insert("raml", Icon::new("\u{e60b}", (66, 165, 245)));
        m.insert("xaml", Icon::new("\u{fb72}", (66, 165, 245)));
        m.insert("haskell", Icon::new("\u{e61f}", (254, 168, 62)));
        m.insert("lua", Icon::new("\u{e620}", (66, 165, 245)));
        m.insert("clojure", Icon::new("\u{e76a}", (100, 221, 23)));
        m.insert("groovy", Icon::new("\u{f2a6}", (41, 198, 218)));
        m.insert("r", Icon::new("\u{fcd2}", (25, 118, 210)));
        m.insert("dart", Icon::new("\u{e798}", (87, 182, 240)));
        m.insert("mxml", Icon::new("\u{f72d}", (254, 168, 62)));
        m.insert("assembly", Icon::new("\u{f471}", (250, 109, 63)));
        m.insert("vue", Icon::new("\u{fd42}", (65, 184, 131)));
        m.insert("vue-config", Icon::new("\u{fd42}", (58, 121, 110)));
        m.insert("lock", Icon::new("\u{f83d}", (255, 213, 79)));
        m.insert("handlebars", Icon::new("\u{e60f}", (250, 111, 66)));
        m.insert("perl", Icon::new("\u{e769}", (149, 117, 205)));
        m.insert("elixir", Icon::new("\u{e62d}", (149, 117, 205)));
        m.insert("erlang", Icon::new("\u{e7b1}", (244, 68, 62)));
        m.insert("twig", Icon::new("\u{e61c}", (155, 185, 47)));
        m.insert("julia", Icon::new("\u{e624}", (134, 82, 159)));
        m.insert("elm", Icon::new("\u{e62c}", (96, 181, 204)));
        m.insert("smarty", Icon::new("\u{f834}", (255, 207, 60)));
        m.insert("stylus", Icon::new("\u{e600}", (192, 202, 51)));
        m.insert("verilog", Icon::new("\u{fb19}", (250, 111, 66)));
        m.insert("robot", Icon::new("\u{fba7}", (249, 89, 63)));
        m.insert("solidity", Icon::new("\u{fcb9}", (3, 136, 209)));
        m.insert("yang", Icon::new("\u{fb7e}", (66, 165, 245)));
        m.insert("vercel", Icon::new("\u{f47e}", (207, 216, 220)));
        m.insert("applescript", Icon::new("\u{f302}", (120, 144, 156)));
        m.insert("cake", Icon::new("\u{f5ea}", (250, 111, 66)));
        m.insert("nim", Icon::new("\u{f6a4}", (255, 202, 61)));
        m.insert("todo", Icon::new("\u{f058}", (124, 179, 66)));
        m.insert("nix", Icon::new("\u{f313}", (80, 117, 193)));
        m.insert("http", Icon::new("\u{f484}", (66, 165, 245)));
        m.insert("webpack", Icon::new("\u{fc29}", (142, 214, 251)));
        m.insert("ionic", Icon::new("\u{e7a9}", (79, 143, 247)));
        m.insert("gulp", Icon::new("\u{e763}", (229, 61, 58)));
        m.insert("yarn", Icon::new("\u{f61a}", (44, 142, 187)));
        m.insert("android", Icon::new("\u{f531}", (139, 195, 74)));
        m.insert("tune", Icon::new("\u{fb69}", (251, 193, 60)));
        m.insert("contributing", Icon::new("\u{f64d}", (255, 202, 61)));
        m.insert("readme", Icon::new("\u{f7fb}", (66, 165, 245)));
        m.insert("changelog", Icon::new("\u{fba6}", (139, 195, 74)));
        m.insert("credits", Icon::new("\u{f75f}", (156, 204, 101)));
        m.insert("authors", Icon::new("\u{f0c0}", (244, 68, 62)));
        m.insert("favicon", Icon::new("\u{e623}", (255, 213, 79)));
        m.insert("karma", Icon::new("\u{e622}", (60, 190, 174)));
        m.insert("travis", Icon::new("\u{e77e}", (203, 58, 73)));
        m.insert("heroku", Icon::new("\u{e607}", (105, 99, 185)));
        m.insert("gitlab", Icon::new("\u{f296}", (226, 69, 57)));
        m.insert("bower", Icon::new("\u{e61a}", (239, 88, 60)));
        m.insert("conduct", Icon::new("\u{f64b}", (205, 220, 57)));
        m.insert("jenkins", Icon::new("\u{e767}", (240, 214, 183)));
        m.insert("code-climate", Icon::new("\u{f7f4}", (238, 238, 238)));
        m.insert("log", Icon::new("\u{f719}", (175, 180, 43)));
        m.insert("ejs", Icon::new("\u{e618}", (255, 202, 61)));
        m.insert("grunt", Icon::new("\u{e611}", (251, 170, 61)));
        m.insert("django", Icon::new("\u{e71d}", (67, 160, 71)));
        m.insert("makefile", Icon::new("\u{f728}", (239, 83, 80)));
        m.insert("bitbucket", Icon::new("\u{f171}", (31, 136, 229)));
        m.insert("d", Icon::new("\u{e7af}", (244, 68, 62)));
        m.insert("mdx", Icon::new("\u{f853}", (255, 202, 61)));
        m.insert("azure-pipelines", Icon::new("\u{f427}", (20, 101, 192)));
        m.insert("azure", Icon::new("\u{fd03}", (31, 136, 229)));
        m.insert("razor", Icon::new("\u{f564}", (66, 165, 245)));
        m.insert("asciidoc", Icon::new("\u{f718}", (244, 68, 62)));
        m.insert("edge", Icon::new("\u{f564}", (239, 111, 60)));
        m.insert("scheme", Icon::new("\u{fb26}", (244, 68, 62)));
        m.insert("3d", Icon::new("\u{e79b}", (40, 182, 246)));
        m.insert("svg", Icon::new("\u{fc1f}", (255, 181, 62)));
        m.insert("moonscript", Icon::new("\u{f186}", (251, 193, 60)));
        m.insert("codeowners", Icon::new("\u{f507}", (175, 180, 43)));
        m.insert("disc", Icon::new("\u{e271}", (176, 190, 197)));
        m.insert("fortran", Icon::new("F", (250, 111, 66)));
        m.insert("tcl", Icon::new("\u{fbd1}", (239, 83, 80)));
        m.insert("liquid", Icon::new("\u{e275}", (40, 182, 246)));
        m.insert("prolog", Icon::new("\u{e7a1}", (239, 83, 80)));
        m.insert("husky", Icon::new("\u{f8e8}", (229, 229, 229)));
        m.insert("coconut", Icon::new("\u{f5d2}", (141, 110, 99)));
        m.insert("sketch", Icon::new("\u{f6c7}", (255, 194, 61)));
        m.insert("pawn", Icon::new("\u{e261}", (239, 111, 60)));
        m.insert("commitlint", Icon::new("\u{fc16}", (43, 150, 137)));
        m.insert("dhall", Icon::new("\u{f448}", (120, 144, 156)));
        m.insert("dune", Icon::new("\u{f7f4}", (244, 127, 61)));
        m.insert("shaderlab", Icon::new("\u{fbad}", (25, 118, 210)));
        m.insert("command", Icon::new("\u{fb32}", (175, 188, 194)));
        m.insert("stryker", Icon::new("\u{f05b}", (239, 83, 80)));
        m.insert("modernizr", Icon::new("\u{e720}", (234, 72, 99)));
        m.insert("roadmap", Icon::new("\u{fb6d}", (48, 166, 154)));
        m.insert("debian", Icon::new("\u{f306}", (211, 61, 76)));
        m.insert("ubuntu", Icon::new("\u{f31c}", (214, 73, 53)));
        m.insert("arch", Icon::new("\u{f303}", (33, 142, 202)));
        m.insert("redhat", Icon::new("\u{f316}", (231, 61, 58)));
        m.insert("gentoo", Icon::new("\u{f30d}", (148, 141, 211)));
        m.insert("linux", Icon::new("\u{e712}", (238, 207, 55)));
        m.insert("raspberry-pi", Icon::new("\u{f315}", (208, 60, 76)));
        m.insert("manjaro", Icon::new("\u{f312}", (73, 185, 90)));
        m.insert("opensuse", Icon::new("\u{f314}", (111, 180, 36)));
        m.insert("fedora", Icon::new("\u{f30a}", (52, 103, 172)));
        m.insert("freebsd", Icon::new("\u{f30c}", (175, 44, 42)));
        m.insert("centOS", Icon::new("\u{f304}", (157, 83, 135)));
        m.insert("alpine", Icon::new("\u{f300}", (14, 87, 123)));
        m.insert("routing", Icon::new("\u{fb40}", (67, 160, 71)));
        m.insert("laravel", Icon::new("\u{e73f}", (248, 80, 81)));
        m.insert("zig", Icon::new("Z", (249, 169, 60)));
        m.insert("h", Icon::new("h", (2, 119, 189)));
        m.insert("hpp", Icon::new("h", (2, 119, 189)));
        m.insert("dir-config", Icon::new("\u{e5fc}", (32, 173, 194)));
        m.insert("dir-controller", Icon::new("\u{e5fc}", (255, 194, 61)));
        m.insert("dir-git", Icon::new("\u{e5fb}", (250, 111, 66)));
        m.insert("dir-github", Icon::new("\u{e5fd}", (84, 110, 122)));
        m.insert("dir-npm", Icon::new("\u{e5fa}", (203, 56, 55)));
        m.insert("dir-include", Icon::new("\u{f756}", (3, 155, 229)));
        m.insert("dir-import", Icon::new("\u{f756}", (175, 180, 43)));
        m.insert("dir-code", Icon::new("\u{f19f6}", (224, 177, 77)));
        m.insert("dir-upload", Icon::new("\u{f758}", (250, 111, 66)));
        m.insert("dir-download", Icon::new("\u{f74c}", (76, 175, 80)));
        m.insert("dir-secure", Icon::new("\u{f74f}", (249, 169, 60)));
        m.insert("dir-environment", Icon::new("\u{f74e}", (102, 187, 106)));
        return m;
    };

    pub static DIR_ICONS: HashMap<&'static str, &'static str> = {
        let mut m = HashMap::new();
        m.insert("config", "dir-config");
        m.insert(".config", "dir-config");
        m.insert("configs","dir-config");
        m.insert("configuration", "dir-config");
        m.insert(".git", "dir-git");
        m.insert("github", "dir-github");
        m.insert(".github", "dir-github");
        m.insert("node_modules", "dir-npm");
        m.insert("src", "dir-code");
        m.insert("lib", "dir-code");
        m.insert("include", "dir-include");
        m.insert("download", "dir-download");
        m.insert("upload", "dir-upload");
        m.insert("downloads", "downloads");
        m.insert("pictures", "pictures");
        m.insert("picture", "pictures");
        m.insert("images", "pictures");
        m.insert("image", "pictures");
        m.insert("music", "music");
        m.insert("videos", "videos");
        return m;
    };

  pub static EXT_ICONS: HashMap<&'static str, &'static str> = {
        let mut m = HashMap::new();
        m.insert("html", "html");
        m.insert("htm", "html");
        m.insert("xhtml", "html");
        m.insert("html_vm", "html");
        m.insert("asp", "html");
        m.insert("jade", "pug");
        m.insert("pug", "pug");
        m.insert("md", "markdown");
        m.insert("markdown", "markdown");
        m.insert("rst", "markdown");
        m.insert("mdx", "mdx");
        m.insert("blink", "blink");
        m.insert("css", "css");
        m.insert("scss", "sass");
        m.insert("sass", "sass");
        m.insert("less", "less");
        m.insert("styl", "stylus");
        m.insert("pcss", "postcss");
        m.insert("sss", "postcss");
        m.insert("ejs", "ejs");
        m.insert("hbs", "handlebars");
        m.insert("mustache", "handlebars");
        m.insert("twig", "twig");
        m.insert("liquid", "liquid");
        m.insert("edge", "edge");
        m.insert("jinja", "jinja");
        m.insert("jinja2", "jinja");
        m.insert("j2", "jinja");
        m.insert("jinja-html", "jinja");
        m.insert("json", "json");
        m.insert("json5", "json");
        m.insert("jsonl", "json");
        m.insert("ndjson", "json");
        m.insert("tsbuildinfo", "json");
        m.insert("yaml", "yaml");
        m.insert("yml", "yaml");
        m.insert("xml", "xml");
        m.insert("plist", "xml");
        m.insert("xsd", "xml");
        m.insert("dtd", "xml");
        m.insert("xsl", "xml");
        m.insert("xslt", "xml");
        m.insert("resx", "xml");
        m.insert("iml", "xml");
        m.insert("xquery", "xml");
        m.insert("toml", "settings");
        m.insert("ini", "settings");
        m.insert("dlc", "settings");
        m.insert("config", "settings");
        m.insert("conf", "settings");
        m.insert("properties", "settings");
        m.insert("prop", "settings");
        m.insert("settings", "settings");
        m.insert("env", "tune");
        m.insert("http", "http");
        m.insert("rest", "http");
        m.insert("js", "javascript");
        m.insert("esx", "javascript");
        m.insert("mjs", "javascript");
        m.insert("jsx", "react");
        m.insert("tsx", "react_ts");
        m.insert("ts", "typescript");
        m.insert("coffee", "coffee");
        m.insert("cson", "coffee");
        m.insert("iced", "coffee");
        m.insert("rs", "rust");
        m.insert("go", "go");
        m.insert("c", "c");
        m.insert("m", "c");
        m.insert("i", "c");
        m.insert("mi", "c");
        m.insert("h", "h");
        m.insert("cpp", "cpp");
        m.insert("cc", "cpp");
        m.insert("cxx", "cpp");
        m.insert("c++", "cpp");
        m.insert("cp", "cpp");
        m.insert("mm", "cpp");
        m.insert("hpp", "hpp");
        m.insert("hh", "hpp");
        m.insert("hxx", "hpp");
        m.insert("h++", "hpp");
        m.insert("inl", "hpp");
        m.insert("java", "java");
        m.insert("jar", "java");
        m.insert("jsp", "java");
        m.insert("kt", "kotlin");
        m.insert("kts", "kotlin");
        m.insert("groovy", "groovy");
        m.insert("gradle", "gradle");
        m.insert("clj", "clojure");
        m.insert("cljs", "clojure");
        m.insert("cljc", "clojure");
        m.insert("cs", "csharp");
        m.insert("csx", "csharp");
        m.insert("fs", "fsharp");
        m.insert("fsx", "fsharp");
        m.insert("fsi", "fsharp");
        m.insert("fsproj", "fsharp");
        m.insert("xaml", "xaml");
        m.insert("cshtml", "razor");
        m.insert("vbhtml", "razor");
        m.insert("py", "python");
        m.insert("pyc", "python-misc");
        m.insert("whl", "python-misc");
        m.insert("rb", "ruby");
        m.insert("erb", "ruby");
        m.insert("swift", "swift");
        m.insert("php", "php");
        m.insert("lua", "lua");
        m.insert("r", "r");
        m.insert("rmd", "r");
        m.insert("hs", "haskell");
        m.insert("elm", "elm");
        m.insert("ex", "elixir");
        m.insert("exs", "elixir");
        m.insert("eex", "elixir");
        m.insert("leex", "elixir");
        m.insert("erl", "erlang");
        m.insert("ml", "ocaml");
        m.insert("mli", "ocaml");
        m.insert("cmx", "ocaml");
        m.insert("nim", "nim");
        m.insert("dart", "dart");
        m.insert("v", "verilog");
        m.insert("vhd", "verilog");
        m.insert("sol", "solidity");
        m.insert("pas", "pascal");
        m.insert("f", "fortran");
        m.insert("f90", "fortran");
        m.insert("f95", "fortran");
        m.insert("db", "database");
        m.insert("sql", "mysql");
        m.insert("sqlite", "sqlite");
        m.insert("sqlite3", "sqlite");
        m.insert("pgsql", "postgresql");
        m.insert("postgres", "postgresql");
        m.insert("psql", "postgresql");
        m.insert("pdb", "database");
        m.insert("pks", "database");
        m.insert("pkb", "database");
        m.insert("accdb", "database");
        m.insert("mdb", "database");
        m.insert("zip", "zip");
        m.insert("tar", "zip");
        m.insert("gz", "zip");
        m.insert("xz", "zip");
        m.insert("bz2", "zip");
        m.insert("7z", "zip");
        m.insert("rar", "zip");
        m.insert("tgz", "zip");
        m.insert("br", "zip");
        m.insert("bzip2", "zip");
        m.insert("gzip", "zip");
        m.insert("brotli", "zip");
        m.insert("exe", "exe");
        m.insert("msi", "exe");
        m.insert("deb", "debian");
        m.insert("rpm", "redhat");
        m.insert("snap", "ubuntu");
        m.insert("apk", "android");
        m.insert("pdf", "pdf");
        m.insert("doc", "word");
        m.insert("docx", "word");
        m.insert("rtf", "word");
        m.insert("xls", "table");
        m.insert("xlsx", "table");
        m.insert("csv", "table");
        m.insert("tsv", "table");
        m.insert("ppt", "powerpoint");
        m.insert("pptx", "powerpoint");
        m.insert("pps", "powerpoint");
        m.insert("ppsx", "powerpoint");
        m.insert("png", "image");
        m.insert("jpg", "image");
        m.insert("jpeg", "image");
        m.insert("gif", "image");
        m.insert("svg", "svg");
        m.insert("ico", "image");
        m.insert("webp", "image");
        m.insert("psd", "image");
        m.insert("ai", "image");
        m.insert("sketch", "sketch");
        m.insert("afphoto", "image");
        m.insert("stl", "3d");
        m.insert("obj", "3d");
        m.insert("blend", "3d");
        m.insert("fbx", "3d");
        m.insert("gltf", "3d");
        m.insert("glb", "3d");
        m.insert("3ds", "3d");
        m.insert("mp3", "audio");
        m.insert("wav", "audio");
        m.insert("ogg", "audio");
        m.insert("mp4", "video");
        m.insert("webm", "video");
        m.insert("avi", "video");
        m.insert("mov", "video");
        m.insert("mkv", "video");
        m.insert("ttf", "font");
        m.insert("otf", "font");
        m.insert("woff", "font");
        m.insert("woff2", "font");
        m.insert("eot", "font");
        m.insert("dockerfile", "docker");
        m.insert("dockerignore", "docker");
        m.insert("vagrantfile", "vagrant");
        m.insert("jenkinsfile", "jenkins");
        m.insert("tf", "terraform");
        m.insert("tfvars", "terraform");
        m.insert("tfstate", "terraform");
        m.insert("git", "git");
        m.insert("gitignore", "git");
        m.insert("gitattributes", "git");
        m.insert("patch", "git");
        m.insert("sh", "console");
        m.insert("bash", "console");
        m.insert("zsh", "console");
        m.insert("fish", "console");
        m.insert("ps1", "powershell");
        m.insert("psm1", "powershell");
        m.insert("psd1", "powershell");
        m.insert("bat", "console");
        m.insert("cmd", "console");
        m.insert("cer", "certificate");
        m.insert("cert", "certificate");
        m.insert("crt", "certificate");
        m.insert("pub", "key");
        m.insert("key", "key");
        m.insert("pem", "key");
        m.insert("asc", "key");
        m.insert("gpg", "key");
        m.insert("vim", "vim");
        m.insert("vimrc", "vim");
        m.insert("gvimrc", "vim");
        m.insert("log", "log");
        m.insert("lock", "lock");
        m.insert("todo", "todo");
        m.insert("url", "url");
        m.insert("ino", "arduino");
        m
    };
}
